---
title: "Analysis"
author: "Kate Jones, Gianni Spiga"
date: "2022-11-22"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE 
    theme: flatly
    df_print: paged
    
---


# Libraries
```{r, message = FALSE}
library(ggplot2)
library(GGally)
library(plotly)
library(ggcorrplot)
library(car)
```

# Loading in Data
```{r}
aba <- read.table("abalone.txt", sep = ",")
# Fixing Column names 
names(aba) <-
  c(
    "Sex",
    "Length",
    "Diameter",
    "Height",
    "Whole.weight",
    "Shucked.weight",
    "Viscera.weight",
    "Shell.weight",
    "Rings"
  )
head(aba, 15)

# Change Sex into factor 
aba$Sex <- as.factor(aba$Sex)

# Search for NA values
any(is.na(aba))
```

# Visualizations
```{r}
#hist(aba$Length)

# Histrogram of Length
ggplot(data = aba, aes(x = Length)) + geom_histogram(fill = "darkseagreen1")

ggplot(data = aba, aes(x = Diameter)) + geom_histogram(fill = "darkseagreen2")

ggplot(data = aba, aes(x = Height)) + geom_histogram(fill = "darkseagreen3")

ggplot(data = aba, aes(x = Whole.weight)) + geom_histogram(fill = "darkseagreen4")

ggplot(data = aba, aes(x = Shucked.weight)) + geom_histogram(fill = "darkseagreen")

ggplot(data = aba, aes(x = Viscera.weight)) + geom_histogram(fill = "darkseagreen1")

ggplot(data = aba, aes(x = Shell.weight)) + geom_histogram(fill = "darkseagreen2")

ggplot(data = aba, aes(x = Rings)) + geom_histogram(bins = 29, fill = "darkseagreen3")

# Scatterplot of Diameter and Height
ggplot(data = aba, aes(x = Diameter, y = Height)) + geom_point()

# Scatter plot of Diameter, Rings, and Sex with plotly
ggplotly(ggplot(data = aba, aes(
  x = Diameter, y = Rings, color = Sex
)) + geom_point() + scale_color_manual(values = c("#f8674f", "#2887c8", "#9fe2bf")))
```
# Checking relationships amongst variables 

```{r}
corMat <- cor(aba[, -1])
corMat

# heatPlot <- plot_ly(z = corMat, type = "heatmap")
# heatPlot
ggcorrplot(
  corMat,
  type = "lower",
  outline.col = "white",
  lab = TRUE,
  color = c("#f8674f", "#2887c8", "#9fe2bf")
)

# Lots of high multicollinearity!! 
```

```{r}
# Initial Model 
fullMod <- lm(Rings ~ ., data = aba)
summary(fullMod)
anova(fullMod)
vif(fullMod)
```

The VIF indicates that we have high multicollinearity and we will need to build a model accordingly. We now check if our response variable needs a transformation.

```{r}
### Checking Assumptions
plot(fullMod)

# Check for transformation 
library(MASS)
boxcox(fullMod)

# Now we use full log model
logFullMod <- lm(log(Rings) ~ ., data = aba)
summary(logFullMod)
plot(logFullMod)
```

# Addressing Multicollinearity

```{r}
# Remove Shucked weight since full weight would be easier process
noShuckMod <- lm(log(Rings) ~ .-Shucked.weight, data = aba)
summary(noShuckMod)

# Male sex is becoming obviously insignifcant, so lets make new column where abalone is infant or not
aba$Infant <- as.factor(ifelse(aba$Sex == 'I', 'Y','N'))
aba$Infant

# Clean model by removing Length, and Viscera weight
redMod <- lm(log(Rings) ~ Infant + Diameter + Height+ Whole.weight, data = aba)
summary(redMod)
```

```{r}
anova(logFullMod, redMod)

stepAIC(logFullMod, scope = list("lower" = redMod, "upper" = logFullMod), direction = "forward")
```
